language: python
python:
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - docker pull azdb/lupyne:version2
  - docker run  --env PYTHONPATH=.:/usr/src -dit --name csc483 azdb/lupyne:version2

branches:
  only:
  - main

script: 
  - docker cp ./ csc483:/usr/src
  - docker exec -it csc483 pytest -p no:warnings
