language: python
python:
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - docker pull coady/pylucene
  - pip install lupyne[server]

branches:
  only:
  - main

script: pytest
